services:
  # Minha Aplicação
  db:
    image: postgres:16-alpine
    container_name: rinha-db
    hostname: rinha-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init-rinha-db.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"
    networks:
      - rinha-net

  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    hostname: rinha-redis
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"
    networks:
      - rinha-net

  api1: &api
    build: .
    hostname: api1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - rinha-net
      - payment-processor

  api2:
    <<: *api
    hostname: api2

  load-balancer:
    image: nginx:1.25.5-alpine
    container_name: rinha-load-balancer
    hostname: rinha-load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    restart: unless-stopped
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true

