services:
  db:
    image: postgres:16-alpine
    container_name: rinha-db
    hostname: rinha-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init-rinha-db.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"  # +65MB (era 115MB) - CRÍTICO para evitar OOM
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    hostname: rinha-redis
    command: redis-server --maxmemory 17mb --maxmemory-policy allkeys-lru --save ""
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20MB"   # -43MB (estava subutilizado - 2.07MB usado)
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  api1: &api
    build: .
    hostname: api1
    command: bun --smol run src/index.ts
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.46"
          memory: "75MB"
    networks:
      - rinha-net
      - payment-processor
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  api2:
    <<: *api
    hostname: api2

  load-balancer:
    image: nginx:1.25.5-alpine
    container_name: rinha-load-balancer
    hostname: rinha-load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"      # +0.05 CPU para resolver EOF
          memory: "30MB"   # +8MB para buffers maiores
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true